### ISSUE TITLE
Cannot build examples

### ISSUE THREAD

**Issue by kevglynn** [dato-code/GraphLab-Create-SDK#17]
When I run the command `cd graphlab-sdk && make`, the examples won't build, and I get the following error:

`$ cd graphlab-sdk && make`
`g++ -o sdk_example/example1.so -std=c++11 -I . -shared -fPIC --stdlib=libc++ -undefined `
`dynamic_lookup sdk_example/example1.cpp`
`g++: error: unrecognized command line option ‘--stdlib=libc++’`
`make: *** [sdk_example/example1.so] Error 1`
`graphlab-sdk $ `

Is it necessary to modify the .cpp file, like here [on stackoverflow](http://stackoverflow.com/questions/30794588/g-error-unrecognized-command-line-option-stdlib-libstdc)?

**Comment by kevglynn** [comment]
I should have added, Mac OS X 10.11.5, GLC 1.10, xcode is installed, etc.

**Comment by ylow** [comment]
Hi, can you try replacing g++ with clang++ in the Makefile.

**Comment by kevglynn** [comment]
Yes that worked perfectly. Thank you.
