### ISSUE TITLE
Not able to import 

### ISSUE THREAD

**Issue by raazesh-sainudiin** [dato-code/GraphLab-Create-SDK#6]
HI,
I want to have a tinker with dato.

Followed the steps on my ubuntu 14.04 LTS and successfully installed dato-core.  
Then also installed GraphLab-Create-SDK.

~/software/dato/graphlab-sdk$ make
g++ -o sdk_example/example1.so -std=c++11 -I . -shared -fPIC sdk_example/example1.cpp
g++ -o sdk_example/sgraph_edge_deduplication.so -std=c++11 -I . -shared -fPIC sdk_example/sgraph_edge_deduplication.cpp
g++ -o sdk_example/sgraph_weighted_pagerank.so -std=c++11 -I . -shared -fPIC sdk_example/sgraph_weighted_pagerank.cpp

~/software/dato/graphlab-sdk$ ls
boost  doxygen     graphlab  Makefile           README.md
doc    export.hpp  LICENSE   makefile_template  sdk_example

BUT can't do the ipython example with 'import graphlab' (do I need to do some other step to make sure ipython can find graphlab?)

~/software/dato/graphlab-sdk$ ipython 
Python 2.7.9 (default, Jul 27 2015, 08:25:19) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import graphlab
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4b66ad388e97> in <module>()
----> 1 import graphlab

ImportError: No module named graphlab

In [2]: exit

Also, I could not follow the simple steps for the C++ example.
The example.cpp file is:
~/software/dato/graphlab-sdk/gl_extensions$ cat example.cpp 
#include <graphlab/sdk/toolkit_function_macros.hpp>
using namespace graphlab;
int add_integers(int a, int b) {
  return a + b;
}
BEGIN_FUNCTION_REGISTRATION
REGISTER_FUNCTION(add_integers, "a", "b"); // provide named parameters
END_FUNCTION_REGISTRATION

~/software/dato/graphlab-sdk/gl_extensions$ ls
example.cpp

I am able to successfully do:
~/software/dato/graphlab-sdk/gl_extensions$ g++ -std=c++11 example.cpp -I ../ -shared -fPIC -o example.so
~/software/dato/graphlab-sdk/gl_extensions$ ls
example.cpp  example.so

But then I cannot import in python.

I guess I am missing some basic steps to get 'import graphlab' to work in ipython.

Thanks,

Raaz

**Comment by ylow** [comment]
dato-core is almost "deprecated" at the moment. We will be open sourcing a new package of it which is much cleaner under the BSD license. For now, the SDK tracks against the ABI in the official GraphLab Create package. You should go to the http://dato.com/ and get GraphLab Create to have it work correctly with the SDK.
